### ISSUE TITLE
IndexError while running operations

### ISSUE THREAD

**Issue by idocal** [zhangqianhui/Conditional-Gans#1]
Hi, I get the following error while running python main.py --operation 1 , using MNIST dataset.

Traceback (most recent call last):
  File "main.py", line 30, in <module>
    tf.app.run()
  File "/Users/Ido/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 27, in main
    , model_path= FLAGS.model_path , visua_path=FLAGS.visua_path)
  File "/Users/Ido/Conditional-Gans/model_mnist.py", line 37, in dcgan
    data_array , data_y = load_mnist(data_name)
  File "/Users/Ido/Conditional-Gans/utils.py", line 48, in load_mnist
    y_vec[i, y[i]] = 1
**IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**

Any ideas?
Thanks!

**Comment by zhangqianhui** [comment]
y_vec[i,int(y[i])]= 1 , you can try it.
